import pygame

WIDTH, HEIGHT = 800, 480

OBJECT_WIDTH = 32
OBJECT_HEIGHT = 32
BEAR_SAFETY_ZONE = OBJECT_WIDTH * 2

BEAR_SPEED = 4
OBJECT_SPEED = 2

NUM_OBJECTS = 2

SCORE_INCREASE = 100

EV_OBJECT_TOUCH = pygame.USEREVENT + 1

FPS = 75